/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-entity-init.ts
 * It automatically registers all entity configurations found in src/domains.
 */

import { registerLazyLoader } from "@/core/entities/registry"

export function initializeEntityConfigs() {
  registerLazyLoader("connection", () => import("../../../domains/system/connection/connection.config"))
  registerLazyLoader("enum", () => import("../../../domains/system/enum/enum.config"))
  registerLazyLoader("example", () => import("../../../domains/operations/example/example.config"))
  registerLazyLoader("notification", () => import("../../../domains/notifications/notification.config"))
  registerLazyLoader("role", () => import("../../../domains/system/role/role.config"))
  registerLazyLoader("ticket", () => import("../../../domains/tickets/ticket.config"))
  registerLazyLoader("user", () => import("../../../domains/user/user.config"))
  registerLazyLoader("user-otp", () => import("../../../domains/user/user-otp/user-otp.config"))
}
