/**
 * Font registry for the Theme Studio font picker.
 *
 * ALL families are SELF-HOSTED (no CDN):
 *   - The bundled defaults (Inter / IBM Plex Arabic / JetBrains Mono) via next/font/local.
 *   - A curated menu of Google families self-hosted as woff2 under
 *     /public/fonts/web (generated by scripts/fetch-local-fonts.sh) and declared
 *     in /public/fonts/web-fonts.css.
 *   - The 29LT PBL brand fonts under /public/fonts/brand, declared in
 *     /public/fonts/brand-fonts.css.
 * The stylesheets are linked from src/app/layout.tsx.
 *
 * Picking a font writes its `family` to the `--font-sans` AND `--font-arabic`
 * theme tokens (the values the whole app consumes). Latin-only families carry
 * an Arabic fallback in the stack so Arabic text still renders well. The
 * "System default" option clears those tokens (use the bundled fonts).
 */

export type FontCategory = "default" | "brand" | "arabic" | "sans" | "serif"

export interface FontOption {
  /** Stable id stored as the picker selection. */
  id: string
  /** English display label. */
  label: string
  /** Native/Arabic display label. */
  labelAr: string
  /** Grouping for the picker. */
  category: FontCategory
  /**
   * CSS font-family stack written to --font-sans / --font-arabic.
   * Empty string = clear the override (use the bundled default fonts).
   */
  family: string
  /** Short sample shown in the picker (Latin + Arabic). */
  sample: string
}

/** Sentinel id for "use the app's bundled default fonts". */
export const DEFAULT_FONT_ID = "default"

/** Arabic fallback appended to Latin-only families so Arabic copy still renders. */
const AR_FALLBACK = '"Noto Sans Arabic", "IBM Plex Sans Arabic", system-ui, sans-serif'
const SAMPLE = "Aa Bb 123 — أبجد هوز"

const arabic = (face: string): string => `"${face}", system-ui, sans-serif`
const sans = (face: string): string => `"${face}", ${AR_FALLBACK}`
const serif = (face: string): string => `"${face}", "Amiri", Georgia, serif`

export const FONT_OPTIONS: FontOption[] = [
  {
    id: DEFAULT_FONT_ID,
    label: "System default (Inter · IBM Plex Arabic)",
    labelAr: "الافتراضي",
    category: "default",
    family: "",
    sample: SAMPLE,
  },

  // ─── PBL / 29LT brand fonts ───────────────────────────────────────────────
  { id: "kaff", label: "29LT Kaff (brand)", labelAr: "29LT كاف", category: "brand", family: arabic("29LT Kaff"), sample: SAMPLE },
  {
    id: "adaround",
    label: "29LT AdaRound (brand)",
    labelAr: "29LT أداراوند",
    category: "brand",
    family: '"29LT AdaRound", "29LT Kaff", system-ui, sans-serif',
    sample: SAMPLE,
  },
  { id: "bukra", label: "29LT Bukra (brand)", labelAr: "29LT بكرة", category: "brand", family: arabic("29LT Bukra"), sample: SAMPLE },

  // ─── Arabic-first families (cover Arabic + Latin) ─────────────────────────
  { id: "cairo", label: "Cairo", labelAr: "القاهرة", category: "arabic", family: arabic("Cairo"), sample: SAMPLE },
  { id: "tajawal", label: "Tajawal", labelAr: "تجوال", category: "arabic", family: arabic("Tajawal"), sample: SAMPLE },
  { id: "almarai", label: "Almarai", labelAr: "المراعي", category: "arabic", family: arabic("Almarai"), sample: SAMPLE },
  { id: "rubik", label: "Rubik", labelAr: "روبيك", category: "arabic", family: arabic("Rubik"), sample: SAMPLE },
  { id: "changa", label: "Changa", labelAr: "تشانجا", category: "arabic", family: arabic("Changa"), sample: SAMPLE },
  { id: "el-messiri", label: "El Messiri", labelAr: "المسيري", category: "arabic", family: arabic("El Messiri"), sample: SAMPLE },
  { id: "noto-kufi", label: "Noto Kufi Arabic", labelAr: "نوتو كوفي", category: "arabic", family: arabic("Noto Kufi Arabic"), sample: SAMPLE },
  {
    id: "noto-sans-arabic",
    label: "Noto Sans Arabic",
    labelAr: "نوتو سانس",
    category: "arabic",
    family: arabic("Noto Sans Arabic"),
    sample: SAMPLE,
  },

  // ─── Latin sans (with Arabic fallback) ────────────────────────────────────
  { id: "roboto", label: "Roboto", labelAr: "روبوتو", category: "sans", family: sans("Roboto"), sample: SAMPLE },
  { id: "open-sans", label: "Open Sans", labelAr: "أوبن سانس", category: "sans", family: sans("Open Sans"), sample: SAMPLE },
  { id: "poppins", label: "Poppins", labelAr: "بوبينز", category: "sans", family: sans("Poppins"), sample: SAMPLE },
  { id: "montserrat", label: "Montserrat", labelAr: "مونتسيرات", category: "sans", family: sans("Montserrat"), sample: SAMPLE },
  { id: "lato", label: "Lato", labelAr: "لاتو", category: "sans", family: sans("Lato"), sample: SAMPLE },
  { id: "nunito", label: "Nunito", labelAr: "نونيتو", category: "sans", family: sans("Nunito"), sample: SAMPLE },
  { id: "dm-sans", label: "DM Sans", labelAr: "دي إم سانس", category: "sans", family: sans("DM Sans"), sample: SAMPLE },
  {
    id: "plus-jakarta-sans",
    label: "Plus Jakarta Sans",
    labelAr: "بلس جاكرتا",
    category: "sans",
    family: sans("Plus Jakarta Sans"),
    sample: SAMPLE,
  },
  { id: "manrope", label: "Manrope", labelAr: "مانروب", category: "sans", family: sans("Manrope"), sample: SAMPLE },
  { id: "work-sans", label: "Work Sans", labelAr: "ورك سانس", category: "sans", family: sans("Work Sans"), sample: SAMPLE },
  { id: "source-sans-3", label: "Source Sans 3", labelAr: "سورس سانس", category: "sans", family: sans("Source Sans 3"), sample: SAMPLE },
  { id: "raleway", label: "Raleway", labelAr: "رالواي", category: "sans", family: sans("Raleway"), sample: SAMPLE },

  // ─── Serif / display ──────────────────────────────────────────────────────
  { id: "markazi", label: "Markazi Text (serif)", labelAr: "مركزي", category: "serif", family: serif("Markazi Text"), sample: SAMPLE },
  { id: "amiri", label: "Amiri (serif)", labelAr: "أميري", category: "serif", family: serif("Amiri"), sample: SAMPLE },
]

/** Human labels for the picker's category groups. */
export const FONT_CATEGORY_LABELS: Record<FontCategory, string> = {
  default: "Default",
  brand: "PBL brand (29LT)",
  arabic: "Arabic",
  sans: "Sans-serif",
  serif: "Serif & display",
}

/** Theme tokens the font picker writes (kept in sync app-wide). */
export const FONT_TOKEN_KEYS = ["--font-sans", "--font-arabic"] as const

/**
 * Resolve the currently-selected font id from a token map by matching the
 * `--font-sans` value against the registry. Falls back to DEFAULT_FONT_ID when
 * the token is unset, or "custom" for a hand-edited stack we don't recognise.
 */
export function fontIdFromTokens(tokens: Record<string, string>): string {
  const current = tokens["--font-sans"]?.trim()
  if (!current) return DEFAULT_FONT_ID
  const match = FONT_OPTIONS.find(o => o.family && o.family === current)
  return match?.id ?? "custom"
}
