#!/usr/bin/env bash
# One-off: self-host Google Fonts as local woff2 + localize the @font-face CSS.
# Output: public/fonts/web/<slug>/*.woff2 and public/fonts/web-fonts.css
set -uo pipefail
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
ROOT="/d/Acme/Acme-Dashboard"
OUT="$ROOT/public/fonts/web"
CSS="$ROOT/public/fonts/web-fonts.css"
mkdir -p "$OUT"
: > "$CSS"
echo "/* Auto-generated by scripts/fetch-local-fonts.sh — self-hosted Google Fonts (woff2). */" >> "$CSS"

FAMILIES=(
"Cairo|Cairo:wght@400;500;600;700"
"Tajawal|Tajawal:wght@400;500;700"
"Almarai|Almarai:wght@400;700"
"Rubik|Rubik:wght@400;500;600;700"
"Noto Kufi Arabic|Noto+Kufi+Arabic:wght@400;500;700"
"Noto Sans Arabic|Noto+Sans+Arabic:wght@400;500;600;700"
"Markazi Text|Markazi+Text:wght@400;500;600;700"
"Changa|Changa:wght@400;500;600;700"
"El Messiri|El+Messiri:wght@400;500;600;700"
"Amiri|Amiri:wght@400;700"
"Roboto|Roboto:wght@400;500;700"
"Open Sans|Open+Sans:wght@400;500;600;700"
"Poppins|Poppins:wght@400;500;600;700"
"Montserrat|Montserrat:wght@400;500;600;700"
"Lato|Lato:wght@400;700"
"Nunito|Nunito:wght@400;500;600;700"
"DM Sans|DM+Sans:wght@400;500;600;700"
"Plus Jakarta Sans|Plus+Jakarta+Sans:wght@400;500;600;700"
"Manrope|Manrope:wght@400;500;600;700"
"Work Sans|Work+Sans:wght@400;500;600;700"
"Source Sans 3|Source+Sans+3:wght@400;500;600;700"
"Raleway|Raleway:wght@400;500;600;700"
)

for entry in "${FAMILIES[@]}"; do
  name="${entry%%|*}"
  query="${entry##*|}"
  slug="$(echo "$name" | tr '[:upper:] ' '[:lower:]-')"
  mkdir -p "$OUT/$slug"
  css="$(curl -s --max-time 25 -H "User-Agent: $UA" "https://fonts.googleapis.com/css2?family=$query&display=swap")"
  if [ -z "$css" ]; then echo "FAIL(css): $name"; continue; fi
  count=0
  while IFS= read -r line; do
    url="$(echo "$line" | grep -oE 'https://fonts\.gstatic\.com/[^)]+\.woff2' | head -1)"
    if [ -n "$url" ]; then
      fn="$(basename "$url")"
      if [ ! -s "$OUT/$slug/$fn" ]; then
        curl -s --max-time 25 -H "User-Agent: $UA" "$url" -o "$OUT/$slug/$fn"
      fi
      count=$((count+1))
      line="${line/$url//fonts/web/$slug/$fn}"
    fi
    printf '%s\n' "$line" >> "$CSS"
  done <<< "$css"
  echo "OK: $name ($count files)"
done
echo "=== DONE. CSS lines: $(wc -l < "$CSS"), woff2 files: $(find "$OUT" -name '*.woff2' | wc -l) ==="
