#!/usr/bin/env node

import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

/**
 * Entity Initialization Generator
 *
 * Automatically scans src/domains for *.config.ts files
 * and generates src/core/entities/configs/init.ts
 */

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT_DIR = path.resolve(__dirname, "..")
const DOMAINS_DIR = path.join(ROOT_DIR, "src", "domains")
const OUTPUT_FILE = path.join(ROOT_DIR, "src", "core", "entities", "configs", "init.ts")

function findConfigs(dir: string, fileList: string[] = []): string[] {
  const files = fs.readdirSync(dir)
  for (const file of files) {
    const fullPath = path.join(dir, file)
    if (fs.statSync(fullPath).isDirectory()) {
      findConfigs(fullPath, fileList)
    } else if (file.endsWith(".config.ts") || file.endsWith(".config.tsx")) {
      fileList.push(fullPath)
    }
  }
  return fileList
}

// Utility to extract config name from file content.
// Returns both the variable name AND the string index where the export
// declaration starts, so we can anchor the entityName lookup to the
// exported (top-level) config object and ignore nested `entityName:` keys
// that appear earlier in the file (e.g. autocomplete column configs).
function extractConfig(content: string): { configName: string; declIndex: number } | null {
  const match = content.match(/export\s+const\s+(\w+Config)\b/)
  if (!match || match[1] == null || match.index == null) return null
  return { configName: match[1], declIndex: match.index }
}

// Extract the entityName that belongs to the EXPORTED config — the first
// `entityName: "..."` at or after the export declaration. This is the
// top-level key (nested ones in column/field configs appear before it).
function extractEntityName(content: string, declIndex: number, configName: string): string {
  const after = content.slice(declIndex)
  const m = after.match(/entityName:\s*"([^"]+)"/)
  return m?.[1] ?? configName.replace(/Config$/, "").toLowerCase()
}

function generate() {
  process.stdout.write("🔍 Scanning for entity configurations...\n")
  const configFiles = findConfigs(DOMAINS_DIR)
  process.stdout.write(`✨ Found ${configFiles.length} configurations.\n`)

  const registrations: string[] = []
  const usedConfigNames = new Set<string>()
  const usedEntityNames = new Map<string, string>() // entityName -> file (collision guard)

  for (const file of configFiles) {
    // Handle both .ts and .tsx extensions for the import path
    const relativePath = path
      .relative(path.dirname(OUTPUT_FILE), file)
      .replace(/\\/g, "/")
      .replace(/\.tsx?$/, "")

    const content = fs.readFileSync(file, "utf8")
    const extracted = extractConfig(content)

    if (extracted) {
      const { configName, declIndex } = extracted
      if (usedConfigNames.has(configName)) {
        console.warn(`⚠️  Skipping duplicate config name: ${configName} in ${file}`)
        continue
      }
      usedConfigNames.add(configName)

      const entityName = extractEntityName(content, declIndex, configName)

      // Assert no two configs claim the same registry key — this is the
      // collision that silently broke /items and /price-lists.
      const existing = usedEntityNames.get(entityName)
      if (existing) {
        throw new Error(
          `[generate-entity-init] Duplicate entityName "${entityName}" — ` +
            `already registered by ${existing}, now also ${file}. ` +
            `Each config must declare a unique top-level entityName.`,
        )
      }
      usedEntityNames.set(entityName, file)

      registrations.push(
        `  registerLazyLoader("${entityName}", () => import("${relativePath.startsWith(".") ? relativePath : "./" + relativePath}"))`,
      )
    } else {
      console.warn(`⚠️  Could not find exported config in ${file}`)
    }
  }

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-entity-init.ts
 * It automatically registers all entity configurations found in src/domains.
 */

import { registerLazyLoader } from "@/core/entities/registry"

export function initializeEntityConfigs() {
${registrations.sort().join("\n")}
}
`

  fs.writeFileSync(OUTPUT_FILE, output)
  process.stdout.write(`✅ Successfully generated ${OUTPUT_FILE}\n`)
}

try {
  generate()
} catch (error) {
  console.error("❌ Generation failed:", error)
  process.exit(1)
}
