/**
 * Pure function: WidgetBuilderSchema → `<id>.widget.ts` source.
 *
 * Output is a small ESM module that re-exports the schema as `widget` plus
 * a `WIDGET_ID` constant. The dashboard runtime imports every widget file
 * from `src/features/dashboard/widgets/` and registers them in a flat
 * Map<id, WidgetBuilderSchema> for the canvas to mount.
 */

import type { WidgetBuilderSchema } from "../types/widget-schema"

export interface GeneratedWidgetFile {
  path: string
  content: string
}

export function generateWidgetFile(schema: WidgetBuilderSchema): GeneratedWidgetFile {
  return {
    path: `src/features/dashboard/widgets/${schema.id}.widget.ts`,
    content: `/**
 * ${schema.titleKey} widget.
 * Auto-generated by /admin/widget-builder. Edit there, not here.
 */

import type { WidgetBuilderSchema } from "@/features/admin-tools/widget-builder/types/widget-schema"

export const WIDGET_ID = "${schema.id}"

export const widget: WidgetBuilderSchema = ${JSON.stringify(schema, null, 2)}
`,
  }
}
